### ISSUE TITLE
埋まるちゃん

### ISSUE THREAD

**Issue by 0x307e** [TinyKitten/SpeedometerPWA#4]
![871FADF4-D39C-475D-B81E-EB739EB148C0](https://user-images.githubusercontent.com/22451396/133779767-b63cb083-c294-4e6e-89c2-04ecfcc539be.png)

**Comment by TinyKitten** [comment]
@makotia リセットボタンのこと？

**Comment by 0x307e** [comment]
@TinyKitten そう
